version = 0.1

[default.deploy.parameters]
stack_name = "berliner-data-pipeline"
resolve_s3 = true
s3_prefix = "berliner-data-pipeline"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
